### ISSUE TITLE
ファイル形式について

### ISSUE THREAD

**Issue by Olivine-Ryo** [geoign/FOB_Pumicerafts#1]
geojson形式のデータも同時にアップロード頂けるととても幸いです。geojson形式ならだれでもgithubの直リンクから読み込めるので利便性が高いかと思います。

**Comment by geoign** [comment]
更新終了後に追加するかもしれませんが、現時点では考えていません。
・更新時に一手間増える問題
・ウェブ上での動的コンテンツへの利用は、防災的メリットをあまりみとめません
Web系GISに読み込む場合は、ogr2ogr等を挟んで対応していただければ。
PythonのGeopandasだとZIP内Shapefileが読めるので2行で済みます。
